version: '3'
services:
  client:
    build: ./client
    ports:
      - '5173:5173'
    env_file:
      - ./client/.env
  admin:
    build: ./admin
    ports:
      - '3000:3000'
    env_file:
      - ./admin/.env
  server:
    build: ./server
    ports:
      - '3045:3045'
    env_file:
      - ./server/.env